package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("Swagger API",
                                              "",
                                              "https://h8tj4utro7.execute-api.us-west-2.amazonaws.com/prod",
                                              new String[] {
                                                  "/join",
                                                  "/create",
                                                  "/update",
                                              },
                                              com.amazonaws.mobile.api.idh8tj4utro7.SwaggerAPIClient.class),
        };

        return apis;
    }
}
